version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: call-center-db
    environment:
      POSTGRES_DB: call_center
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - call-center-network

  redis:
    image: redis:7-alpine
    container_name: call-center-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - call-center-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: call-center-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - call-center-network

  freeswitch:
    build:
      context: ./docker/freeswitch
      dockerfile: Dockerfile
    container_name: call-center-freeswitch
    ports:
      - "5060:5060/udp"
      - "5061:5061/tcp"
      - "8021:8021"
      - "16384-16394:16384-16394/udp"
    volumes:
      - ./docker/freeswitch/conf:/usr/local/freeswitch/conf
      - freeswitch_logs:/usr/local/freeswitch/log
    networks:
      - call-center-network
    depends_on:
      - postgres
      - redis

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: call-center-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - call-center-network
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: call-center-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/call_center
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      FREESWITCH_HOST: freeswitch
      FREESWITCH_PORT: 8021
      FREESWITCH_PASSWORD: ClueCon
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - call-center-network
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - freeswitch

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: call-center-frontend
    environment:
      VITE_API_URL: http://localhost:3001
      VITE_WS_URL: ws://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - call-center-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  freeswitch_logs:

networks:
  call-center-network:
    driver: bridge